### PR TITLE
added button hover animation and navbar background 

### PR DESCRIPTION
**Pull request by harmanpreet7916**
In first commit  I have added button hover property and commented previous button css and taking class name same as previous i have written button css. and also added a background in heading HACKTOBER FEST . 
In second commit i have done the task1 by adding my photo and updating both files.

### CODE REVIEW

**Comment by harmanpreet7916** [comment]
please review and give feedback sir.

**Review by sakpab2602 — COMMENTED** [review]
@harmanpreet7916  this looks really very nice! the profile card buttons look amazing, if you can also try to make it responsive, it will really be appreciated!

**Comment by harmanpreet7916** [comment]
ok I will try to make it responsive. I think it was not responsive previously as I have used already used dimensions.

**Comment by harmanpreet7916** [comment]
I have resolved button overflow issue and made it responsive. also fixed some more issue like margin padding properties which will prevent cards to merge into each other while in half computer screen. also resolved some merge conflicts. review please and label this PR as hacktoberfes-accepted before accepting.

**Comment by hrit-ik** [comment]
Great work!!

**Pull request merged**
