### PR TITLE
Task3-GeorgeET15

### PR DESCRIPTION
**Pull request by GeorgeET15**
1) Added new Nav  bar
2) Added 2 new series
3) Better background
4) Popular series in HomePage
5) Better UI

### CODE REVIEW

**Comment by hrit-ik** [comment]
Great one!!

**Comment by hrit-ik** [comment]
Great one!!
Merged.

**Comment by GeorgeET15** [comment]
Thanks a lot sir :)

**Comment by hrit-ik** [comment]
Yes, you are definitely eligible if you fulfil the prize criteria mentioned in Readme.

**Comment by GeorgeET15** [comment]
Ok sir 😁

**Comment by GeorgeET15** [comment]
Hi sir,

If you don't mind me asking when will be the winners announced.

Regards
George

**Pull request merged**
